#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Classify Song Genres from Audio Data"
description    : >
  Rock or rap? Apply machine learning methods in Python to classify songs into genres.
long_description: |
  Using a dataset comprised of songs of two music genres (Hip-Hop and Rock), you will train a classifier to distinguish between the two genres based only on track information derived from Echonest (now part of Spotify) data for each track. You will first make use of `pandas` and `seaborn` packages in Python for subsetting the data, aggregating information, and creating plots when exploring the data for obvious trends or factors you should be aware of when doing machine learning. Next, you will use the `scikit-learn` package to predict whether you can correctly classify a song's genre based on features such as danceability, energy, acousticness, tempo, etc. You will go over implementations of common algorithms such as PCA, logistic regression, decision trees, and so forth.

  This project lets you apply what you learned in [Supervised Learning with scikit-learn](https://www.datacamp.com/courses/supervised-learning-with-scikit-learn), plus data preprocessing, dimensionality reduction, and machine learning using the `scikit-learn` package.

  The dataset used in this project was compiled from [Echonest](http://the.echonest.com) (now part of Spotify).

time_needed: "60 minutes" # "30/45/60 minutes".


#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 2 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites:
  - 1939
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://authoring.datacamp.com/projects/projects-repo-structure.html#project-yml for IDs
topics:
  - 8
  - 3
  - 4
  - 6

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : python # One of r, python or sql
# The name of the docker image used to run the course
from           : 'python-notebooks-prod:v1.1.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
